name: Go

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: 1.x
    - run: go build -v ./...
    - run: go test -v ./...
